apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: monitoring-serverconf
spec:
  contents: LS0tCmRlZmF1bHRRdWV1ZU1hbmFnZXI6ICdGVEVRTScKTW9uaXRvcmluZzoKICBNZXNzYWdlRmxvdzoKICAgIHB1YmxpY2F0aW9uT246ICdhY3RpdmUnCiAgICBldmVudEZvcm1hdDogJ01vbml0b3JpbmdFdmVudFYyJyAgIyBXaGVuIEJ1c2luZXNzRXZlbnRzLi0ub3V0cHV0Rm9ybWF0IGlzIHhtbCBzZXQgTW9uaXRvcmluZ0V2ZW50VjIgb3IgV01CLCBkZWZhdWx0IE1vbml0b3JpbmdFdmVudFYyCkV2ZW50czoKICBCdXNpbmVzc0V2ZW50czogIyBNb25pdG9yaW5nIGV2ZW50cwogICAgTVE6CiAgICAgIGVuYWJsZWQ6IHRydWUgICAgICAgICAgICAjIFNldCB0cnVlIG9yIGZhbHNlLCBkZWZhdWx0IGZhbHNlCiAgICAgIGZvcm1hdDogJ01vbml0b3JpbmdFdmVudFYyJyAgICAgICAgICAgICAgICAjIFNldCBzdHJpbmcgb3Igbm9uZQogICAgICBvdXRwdXRGb3JtYXQ6ICd4bWwnICAgICAgICMgU2V0IGNvbW1hIHNlcGFyYXRlZCBsaXN0IG9mIG9uZSBvciBtb3JlIG9mIDoganNvbix4bWwuIERlZmF1bHRzIHRvICd4bWwnCg==
  description: "monitoring-serverconf server.conf.yaml"
  type: serverconf
  version: 12.0.12-r1
